version: "3"

services:
  publisher:
    build:
      context: ./publisher
      dockerfile: ../docker/publisher/Dockerfile
  consumer:
    build:
      context: ./consumer
      dockerfile: ../docker/consumer/Dockerfile
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"