services:
  consumer:
    build:
      context: ./consumer
      dockerfile: ../docker/consumer/Dockerfile
    extends:
      file: ./docker-compose.base.yml
      service: app
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbit-1

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
      - rabbit-1

networks:
  rabbit-1:
    name: rabbit-1