services:
  consumer:
    build:
      context: ./consumer
      dockerfile: ../docker/consumer/Dockerfile
    extends:
      file: ./docker-compose.base.yml
      service: app
    networks:
      - rabbit-1

  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbit-1

networks:
  rabbit-1:
    name: rabbit-1